using System.Collections.Generic;
using UnityEngine;

/// Controls an enemy along a path generated by Pathfinder,
/// making each grid cell in the path a temporary steering target.
[RequireComponent(typeof(EnemyLocomotion))]
public class EnemyPathAgent : MonoBehaviour
{
    [Header("References")]
    public Transform player;
    public Pathfinder pathfinder;
    public Transform steeringTarget;

    [Header("Path Settings")]
    public float waypointThreshold = 0.5f;
    public float pathRecalcInterval = 0.5f;

    [Header("Path Visuals")]
    public GameObject pathDotPrefab;

    private List<Vector2Int> currentPath;
    private int pathIndex = 0;
    private float pathRecalcTimer = 0f;

    private readonly List<GameObject> spawnedDots = new List<GameObject>();

    void Update()
    {
        if (player == null || pathfinder == null || steeringTarget == null)
            return;

        pathRecalcTimer -= Time.deltaTime;
        if (pathRecalcTimer <= 0f)
        {
            RecalculatePath();
            pathRecalcTimer = pathRecalcInterval;
        }

        FollowPath();
    }

    private void RecalculatePath()
    {
        Vector2Int start = GridManager.Instance.WorldToGrid(transform.position);
        Vector2Int goal = GridManager.Instance.WorldToGrid(player.position);

        currentPath = pathfinder.FindPath(start, goal);
        pathIndex = 0;

        DrawPathDots();
    }

    private void FollowPath()
    {
        if (currentPath == null || pathIndex >= currentPath.Count)
            return;

        Vector2Int waypointGrid = currentPath[pathIndex];
        Vector3 waypointWorld = GridManager.Instance.GridToWorld(waypointGrid.x, waypointGrid.y);

        steeringTarget.position = waypointWorld;

        if (Vector3.Distance(transform.position, waypointWorld) < waypointThreshold)
        {
            pathIndex++;
        }
    }

    private void DrawPathDots()
    {
        // clear old dots
        for (int i = 0; i < spawnedDots.Count; i++)
        {
            Destroy(spawnedDots[i]);
        }
        spawnedDots.Clear();

        if (currentPath == null)
            return;

        foreach (Vector2Int node in currentPath)
        {
            Vector3 pos = GridManager.Instance.GridToWorld(node.x, node.y);

            // ensure center of tile
            pos += new Vector3(0.0f, 0f, 0.0f);

            GameObject dot = Instantiate(pathDotPrefab, pos, Quaternion.identity);
            spawnedDots.Add(dot);
        }
    }

    private void OnDrawGizmos()
    {
        if (currentPath == null)
            return;

        Gizmos.color = Color.cyan;

        foreach (Vector2Int node in currentPath)
        {
            Vector3 pos = GridManager.Instance.GridToWorld(node.x, node.y);
            pos += new Vector3(0.0f, 0f, -1f);
            Gizmos.DrawSphere(pos, 0.1f);
        }
    }
}