using System.Collections.Generic;
using UnityEngine;


/// <summary>
/// Controls an enemy along a path generated by Pathfinder,
/// making each grid cell in the path a temporary steering target.
/// Works with BFS (basic) or A* (complex).
/// </summary>
[RequireComponent(typeof(EnemyLocomotion))]
public class EnemyPathAgent : MonoBehaviour
{
    [Header("References")]
    public Transform player;               // Assign your Player GameObject
    public Pathfinder pathfinder;          // Assign Pathfinder GameObject
    public Transform steeringTarget;       // Child object used as EnemyLocomotion target

    [Header("Path Settings")]
    public float waypointThreshold = 0.5f; // Distance to consider a waypoint reached
    public float pathRecalcInterval = 0.5f; // Seconds between path recalculation

    private List<Vector2Int> currentPath;
    private int pathIndex = 0;
    private float pathRecalcTimer = 0f;

    void Update()
    {
        if (player == null || pathfinder == null || steeringTarget == null)
            return;

        pathRecalcTimer -= Time.deltaTime;
        if (pathRecalcTimer <= 0f)
        {
            RecalculatePath();
            pathRecalcTimer = pathRecalcInterval;
        }

        FollowPath();
    }

    // Recalculates the path from the enemy's current position to the player's position.
    private void RecalculatePath()
    {
        Vector2Int start = GridManager.Instance.WorldToGrid(transform.position);
        Vector2Int goal = GridManager.Instance.WorldToGrid(player.position);

        currentPath = pathfinder.FindPath(start, goal);
        pathIndex = 0;
    }

    
    // Moves the SteeringTarget along the current path.
    // EnemyLocomotion will follow the target smoothly.
    
    private void FollowPath()
    {
        
        if (currentPath == null || pathIndex >= currentPath.Count)
            return;

        Vector2Int waypointGrid = currentPath[pathIndex];
        Vector3 waypointWorld = GridManager.Instance.GridToWorld(waypointGrid.x, waypointGrid.y);

        // Move the steering target directly to the current waypoint
        steeringTarget.position = waypointWorld;

        // If enemy is close enough to this waypoint, go to next
        if (Vector3.Distance(transform.position, waypointWorld) < waypointThreshold)
        {
            pathIndex++;
        }
    }

    
    /// Debug: Draws the path in the scene view for debugging.
    
    private void OnDrawGizmos()
    {
        if (currentPath == null)
            return;

        Gizmos.color = Color.cyan;
        foreach (Vector2Int node in currentPath)
        {
            Vector3 pos = GridManager.Instance.GridToWorld(node.x, node.y);
            Gizmos.DrawSphere(pos, 0.1f);
        }
    }
}